// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaPeaje.Infrastructure.Data;

#nullable disable

namespace SistemaPeaje.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250721060250_AddModuloTurnosCompleto")]
    partial class AddModuloTurnosCompleto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaPeaje.Core.Entities.Carril", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("EstacionId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("EstacionId");

                    b.ToTable("Carriles");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TipoClienteId")
                        .HasColumnType("int");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("TipoClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.ComandoPlc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("CarrilId")
                        .HasColumnType("int");

                    b.Property<int>("CoilAddress")
                        .HasColumnType("int");

                    b.Property<bool>("ComandoExitoso")
                        .HasColumnType("bit");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEjecucion")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpDestino")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MensajeError")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Puerto")
                        .HasColumnType("int");

                    b.Property<int>("TiempoRespuestaMs")
                        .HasColumnType("int");

                    b.Property<string>("TipoComando")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("UnitId")
                        .HasColumnType("tinyint");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<bool>("ValorEnviado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CarrilId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ComandosPlc");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit");

                    b.Property<int?>("EstacionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("EstacionId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.Estacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Latitud")
                        .HasColumnType("float");

                    b.Property<double?>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Estaciones");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.EventoTransito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CarrilId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoRfid")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DatosAdicionales")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EstacionId")
                        .HasColumnType("int");

                    b.Property<string>("EstadoEvento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PlacaVehiculo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Procesado")
                        .HasColumnType("bit");

                    b.Property<string>("RutaImagen")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SensorId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TipoVehiculoId")
                        .HasColumnType("int");

                    b.Property<int?>("TransaccionId")
                        .HasColumnType("int");

                    b.Property<decimal?>("VelocidadVehiculo")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CarrilId");

                    b.HasIndex("EstacionId");

                    b.HasIndex("TipoVehiculoId");

                    b.HasIndex("TransaccionId");

                    b.ToTable("EventosTransito");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.Liquidacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("AprobadoPorEmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("CreadoPorEmpleadoId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiferenciaCaja")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int?>("EstacionId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoTotalRecaudado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoTotalTransacciones")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NotasAprobacion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("NumeroLiquidacion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("RequiereAprobacion")
                        .HasColumnType("bit");

                    b.Property<int>("TipoLiquidacion")
                        .HasColumnType("int");

                    b.Property<int>("TotalTransacciones")
                        .HasColumnType("int");

                    b.Property<int?>("TurnoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AprobadoPorEmpleadoId");

                    b.HasIndex("CreadoPorEmpleadoId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("EstacionId");

                    b.HasIndex("NumeroLiquidacion")
                        .IsUnique()
                        .HasDatabaseName("IX_Liquidacion_NumeroLiquidacion");

                    b.HasIndex("TurnoId");

                    b.HasIndex("TipoLiquidacion", "FechaInicio", "FechaFin")
                        .HasDatabaseName("IX_Liquidacion_Tipo_Fecha");

                    b.ToTable("Liquidaciones");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.LiquidacionDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CarrilId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaTransaccion")
                        .HasColumnType("datetime2");

                    b.Property<int>("LiquidacionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ObservacionesValidacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TipoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoVehiculo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TransaccionId")
                        .HasColumnType("int");

                    b.Property<bool>("Validado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("LiquidacionId")
                        .HasDatabaseName("IX_LiquidacionDetalle_LiquidacionId");

                    b.HasIndex("TransaccionId");

                    b.ToTable("LiquidacionDetalles");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.LiquidacionDiscrepancia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<int>("LiquidacionId")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoDiscrepancia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NotasResolucion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("Resuelta")
                        .HasColumnType("bit");

                    b.Property<int?>("ResueltoPorEmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("Severidad")
                        .HasColumnType("int");

                    b.Property<int>("TipoDiscrepancia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LiquidacionId")
                        .HasDatabaseName("IX_LiquidacionDiscrepancia_LiquidacionId");

                    b.HasIndex("ResueltoPorEmpleadoId");

                    b.HasIndex("TipoDiscrepancia", "Severidad")
                        .HasDatabaseName("IX_LiquidacionDiscrepancia_Tipo_Severidad");

                    b.ToTable("LiquidacionDiscrepancias");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.PlcCoilConfiguracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccionEspecial")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Direccion")
                        .HasColumnType("int");

                    b.Property<bool>("EsAlarma")
                        .HasColumnType("bit");

                    b.Property<bool>("EstadoActual")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("GenerarEvento")
                        .HasColumnType("bit");

                    b.Property<int>("Indice")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PlcConfiguracionId")
                        .HasColumnType("int");

                    b.Property<string>("TipoEvento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlcConfiguracionId", "Indice")
                        .IsUnique()
                        .HasDatabaseName("IX_PlcCoilConfiguracion_PlcId_Indice");

                    b.ToTable("PlcCoilConfiguraciones");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.PlcConfiguracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CantidadCoils")
                        .HasColumnType("int");

                    b.Property<int>("CarrilId")
                        .HasColumnType("int");

                    b.Property<int>("DireccionInicial")
                        .HasColumnType("int");

                    b.Property<bool>("EstaConectado")
                        .HasColumnType("bit");

                    b.Property<int>("EstacionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HabilitarLoggingPeriodico")
                        .HasColumnType("bit");

                    b.Property<int>("IntervaloMonitoreo")
                        .HasColumnType("int");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Puerto")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimaConexion")
                        .HasColumnType("datetime2");

                    b.Property<byte>("UnitId")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("CarrilId");

                    b.HasIndex("EstacionId");

                    b.HasIndex("Ip", "Puerto")
                        .IsUnique()
                        .HasDatabaseName("IX_PlcConfiguracion_Ip_Puerto");

                    b.ToTable("PlcConfiguraciones");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.RegistroTiempo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ArchivoAdjunto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AutorizadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("DireccionIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<bool>("EsAtraso")
                        .HasColumnType("bit");

                    b.Property<bool>("EsHoraExtra")
                        .HasColumnType("bit");

                    b.Property<bool>("EsValido")
                        .HasColumnType("bit");

                    b.Property<int?>("EstacionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAutorizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodoRegistro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinutosAtraso")
                        .HasColumnType("int");

                    b.Property<string>("MotivoInvalidacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoRegistro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TurnoAsignacionId")
                        .HasColumnType("int");

                    b.Property<int?>("TurnoId")
                        .HasColumnType("int");

                    b.Property<string>("UbicacionGPS")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AutorizadoPorId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("EstacionId");

                    b.HasIndex("TurnoAsignacionId");

                    b.HasIndex("TurnoId");

                    b.ToTable("RegistrosTiempo");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.Tarifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("EsVigente")
                        .HasColumnType("bit");

                    b.Property<int?>("EstacionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVigenciaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVigenciaInicio")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoVehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstacionId");

                    b.HasIndex("TipoVehiculoId");

                    b.ToTable("Tarifas");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.TarjetaRFID", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("TarjetasRFID");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.TipoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("DescuentoPorcentaje")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("DocumentosRequeridos")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EstaExentoPago")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("RequiereValidacionDocumento")
                        .HasColumnType("bit");

                    b.Property<int?>("VigenciaMeses")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TiposCliente");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.TipoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("LimiteCredito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("RequiereAutorizacion")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiereEfectivo")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiereTag")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiereTarjeta")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TiposPago");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.TipoVehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumeroEjes")
                        .HasColumnType("int");

                    b.Property<decimal>("TarifaBase")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TiposVehiculo");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.Transaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CarrilId")
                        .HasColumnType("int");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("EstacionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaTransaccion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroTicket")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PlacaVehiculo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TagRFID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TipoPagoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoVehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarrilId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("EstacionId");

                    b.HasIndex("TipoPagoId");

                    b.HasIndex("TipoVehiculoId");

                    b.ToTable("Transacciones");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("EstacionId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FinDescanso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HoraFinReal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HoraInicioReal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InicioDescanso")
                        .HasColumnType("datetime2");

                    b.Property<int>("MinutosDescanso")
                        .HasColumnType("int");

                    b.Property<int>("MinutosHorasExtras")
                        .HasColumnType("int");

                    b.Property<decimal?>("MontoFinalCaja")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontoHorasExtras")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoInicialCaja")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MotivoCierre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotasAdministrativas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TieneHorasExtras")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalRecaudado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalTransacciones")
                        .HasColumnType("int");

                    b.Property<int>("TotalVehiculos")
                        .HasColumnType("int");

                    b.Property<int?>("TurnoAsignacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("EstacionId");

                    b.HasIndex("TurnoAsignacionId")
                        .IsUnique()
                        .HasFilter("[TurnoAsignacionId] IS NOT NULL");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.TurnoAsignacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("ConfirmadoPorEmpleado")
                        .HasColumnType("bit");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int?>("EmpleadoSustitutoId")
                        .HasColumnType("int");

                    b.Property<int>("EstacionId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaConfirmacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaSustitucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaTurno")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoraFinPrograma")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicioPrograma")
                        .HasColumnType("time");

                    b.Property<string>("InstruccionesEspeciales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MontoInicialCajaAsignado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MotivoRechazo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotivoSustitucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiereSupervisor")
                        .HasColumnType("bit");

                    b.Property<int?>("TurnoTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("EmpleadoSustitutoId");

                    b.HasIndex("EstacionId");

                    b.HasIndex("TurnoTemplateId");

                    b.ToTable("TurnoAsignaciones");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.TurnoEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccionesTomadas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("AfectaOperacion")
                        .HasColumnType("bit");

                    b.Property<string>("ArchivosAdjuntos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AsignadoAId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int?>("EstacionId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraEvento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImpactoOperacional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedidasPreventivas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MontoAfectado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PersonasNotificadas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReportadoPorId")
                        .HasColumnType("int");

                    b.Property<bool>("RequiereNotificacion")
                        .HasColumnType("bit");

                    b.Property<int?>("ResueltoPorId")
                        .HasColumnType("int");

                    b.Property<string>("SolucionAplicada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TurnoAsignacionId")
                        .HasColumnType("int");

                    b.Property<int?>("TurnoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AsignadoAId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("EstacionId");

                    b.HasIndex("ReportadoPorId");

                    b.HasIndex("ResueltoPorId");

                    b.HasIndex("TurnoAsignacionId");

                    b.HasIndex("TurnoId");

                    b.ToTable("TurnoEventos");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.TurnoTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Domingo")
                        .HasColumnType("bit");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit");

                    b.Property<decimal>("FactorHoraExtra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("HoraDescansoInicio")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<bool>("Jueves")
                        .HasColumnType("bit");

                    b.Property<bool>("Lunes")
                        .HasColumnType("bit");

                    b.Property<bool>("Martes")
                        .HasColumnType("bit");

                    b.Property<int>("MaximoHorasExtras")
                        .HasColumnType("int");

                    b.Property<bool>("Miercoles")
                        .HasColumnType("bit");

                    b.Property<int>("MinutosDescanso")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PermiteHorasExtras")
                        .HasColumnType("bit");

                    b.Property<bool>("Sabado")
                        .HasColumnType("bit");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Viernes")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TurnoTemplates");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit");

                    b.Property<int?>("EstacionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Permisos")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("EstacionId");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.Carril", b =>
                {
                    b.HasOne("SistemaPeaje.Core.Entities.Estacion", "Estacion")
                        .WithMany("Carriles")
                        .HasForeignKey("EstacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estacion");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.Cliente", b =>
                {
                    b.HasOne("SistemaPeaje.Core.Entities.TipoCliente", "TipoCliente")
                        .WithMany("Clientes")
                        .HasForeignKey("TipoClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TipoCliente");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.ComandoPlc", b =>
                {
                    b.HasOne("SistemaPeaje.Core.Entities.Carril", "Carril")
                        .WithMany()
                        .HasForeignKey("CarrilId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaPeaje.Core.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaPeaje.Core.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Carril");

                    b.Navigation("Empleado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.Empleado", b =>
                {
                    b.HasOne("SistemaPeaje.Core.Entities.Estacion", "Estacion")
                        .WithMany()
                        .HasForeignKey("EstacionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Estacion");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.EventoTransito", b =>
                {
                    b.HasOne("SistemaPeaje.Core.Entities.Carril", "Carril")
                        .WithMany()
                        .HasForeignKey("CarrilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPeaje.Core.Entities.Estacion", "Estacion")
                        .WithMany()
                        .HasForeignKey("EstacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPeaje.Core.Entities.TipoVehiculo", "TipoVehiculo")
                        .WithMany()
                        .HasForeignKey("TipoVehiculoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaPeaje.Core.Entities.Transaccion", "Transaccion")
                        .WithMany()
                        .HasForeignKey("TransaccionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Carril");

                    b.Navigation("Estacion");

                    b.Navigation("TipoVehiculo");

                    b.Navigation("Transaccion");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.Liquidacion", b =>
                {
                    b.HasOne("SistemaPeaje.Core.Entities.Empleado", "AprobadoPorEmpleado")
                        .WithMany()
                        .HasForeignKey("AprobadoPorEmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaPeaje.Core.Entities.Empleado", "CreadoPorEmpleado")
                        .WithMany()
                        .HasForeignKey("CreadoPorEmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPeaje.Core.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaPeaje.Core.Entities.Estacion", "Estacion")
                        .WithMany()
                        .HasForeignKey("EstacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaPeaje.Core.Entities.Turno", "Turno")
                        .WithMany()
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AprobadoPorEmpleado");

                    b.Navigation("CreadoPorEmpleado");

                    b.Navigation("Empleado");

                    b.Navigation("Estacion");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.LiquidacionDetalle", b =>
                {
                    b.HasOne("SistemaPeaje.Core.Entities.Liquidacion", "Liquidacion")
                        .WithMany("Detalles")
                        .HasForeignKey("LiquidacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaPeaje.Core.Entities.Transaccion", "Transaccion")
                        .WithMany()
                        .HasForeignKey("TransaccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Liquidacion");

                    b.Navigation("Transaccion");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.LiquidacionDiscrepancia", b =>
                {
                    b.HasOne("SistemaPeaje.Core.Entities.Liquidacion", "Liquidacion")
                        .WithMany("Discrepancias")
                        .HasForeignKey("LiquidacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaPeaje.Core.Entities.Empleado", "ResueltoPorEmpleado")
                        .WithMany()
                        .HasForeignKey("ResueltoPorEmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Liquidacion");

                    b.Navigation("ResueltoPorEmpleado");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.PlcCoilConfiguracion", b =>
                {
                    b.HasOne("SistemaPeaje.Core.Entities.PlcConfiguracion", "PlcConfiguracion")
                        .WithMany("CoilsConfiguracion")
                        .HasForeignKey("PlcConfiguracionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlcConfiguracion");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.PlcConfiguracion", b =>
                {
                    b.HasOne("SistemaPeaje.Core.Entities.Carril", "Carril")
                        .WithMany()
                        .HasForeignKey("CarrilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPeaje.Core.Entities.Estacion", "Estacion")
                        .WithMany()
                        .HasForeignKey("EstacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carril");

                    b.Navigation("Estacion");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.RegistroTiempo", b =>
                {
                    b.HasOne("SistemaPeaje.Core.Entities.Empleado", "AutorizadoPor")
                        .WithMany()
                        .HasForeignKey("AutorizadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaPeaje.Core.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPeaje.Core.Entities.Estacion", "Estacion")
                        .WithMany()
                        .HasForeignKey("EstacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaPeaje.Core.Entities.TurnoAsignacion", "TurnoAsignacion")
                        .WithMany("RegistrosTiempo")
                        .HasForeignKey("TurnoAsignacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaPeaje.Core.Entities.Turno", "Turno")
                        .WithMany("RegistrosTiempo")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AutorizadoPor");

                    b.Navigation("Empleado");

                    b.Navigation("Estacion");

                    b.Navigation("Turno");

                    b.Navigation("TurnoAsignacion");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.Tarifa", b =>
                {
                    b.HasOne("SistemaPeaje.Core.Entities.Estacion", "Estacion")
                        .WithMany()
                        .HasForeignKey("EstacionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaPeaje.Core.Entities.TipoVehiculo", "TipoVehiculo")
                        .WithMany("Tarifas")
                        .HasForeignKey("TipoVehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estacion");

                    b.Navigation("TipoVehiculo");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.TarjetaRFID", b =>
                {
                    b.HasOne("SistemaPeaje.Core.Entities.Cliente", "Cliente")
                        .WithMany("TarjetasRFID")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.Transaccion", b =>
                {
                    b.HasOne("SistemaPeaje.Core.Entities.Carril", "Carril")
                        .WithMany("Transacciones")
                        .HasForeignKey("CarrilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPeaje.Core.Entities.Cliente", "Cliente")
                        .WithMany("Transacciones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaPeaje.Core.Entities.Empleado", "Empleado")
                        .WithMany("Transacciones")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaPeaje.Core.Entities.Estacion", "Estacion")
                        .WithMany("Transacciones")
                        .HasForeignKey("EstacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPeaje.Core.Entities.TipoPago", "TipoPago")
                        .WithMany("Transacciones")
                        .HasForeignKey("TipoPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPeaje.Core.Entities.TipoVehiculo", "TipoVehiculo")
                        .WithMany("Transacciones")
                        .HasForeignKey("TipoVehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carril");

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");

                    b.Navigation("Estacion");

                    b.Navigation("TipoPago");

                    b.Navigation("TipoVehiculo");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.Turno", b =>
                {
                    b.HasOne("SistemaPeaje.Core.Entities.Empleado", "Empleado")
                        .WithMany("Turnos")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPeaje.Core.Entities.Estacion", "Estacion")
                        .WithMany()
                        .HasForeignKey("EstacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPeaje.Core.Entities.TurnoAsignacion", "TurnoAsignacion")
                        .WithOne("TurnoEjecutado")
                        .HasForeignKey("SistemaPeaje.Core.Entities.Turno", "TurnoAsignacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empleado");

                    b.Navigation("Estacion");

                    b.Navigation("TurnoAsignacion");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.TurnoAsignacion", b =>
                {
                    b.HasOne("SistemaPeaje.Core.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPeaje.Core.Entities.Empleado", "EmpleadoSustituto")
                        .WithMany()
                        .HasForeignKey("EmpleadoSustitutoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaPeaje.Core.Entities.Estacion", "Estacion")
                        .WithMany()
                        .HasForeignKey("EstacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPeaje.Core.Entities.TurnoTemplate", "TurnoTemplate")
                        .WithMany("TurnoAsignaciones")
                        .HasForeignKey("TurnoTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empleado");

                    b.Navigation("EmpleadoSustituto");

                    b.Navigation("Estacion");

                    b.Navigation("TurnoTemplate");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.TurnoEvento", b =>
                {
                    b.HasOne("SistemaPeaje.Core.Entities.Empleado", "AsignadoA")
                        .WithMany()
                        .HasForeignKey("AsignadoAId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaPeaje.Core.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPeaje.Core.Entities.Estacion", "Estacion")
                        .WithMany()
                        .HasForeignKey("EstacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaPeaje.Core.Entities.Empleado", "ReportadoPor")
                        .WithMany()
                        .HasForeignKey("ReportadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaPeaje.Core.Entities.Empleado", "ResueltoPor")
                        .WithMany()
                        .HasForeignKey("ResueltoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaPeaje.Core.Entities.TurnoAsignacion", "TurnoAsignacion")
                        .WithMany("Eventos")
                        .HasForeignKey("TurnoAsignacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaPeaje.Core.Entities.Turno", "Turno")
                        .WithMany("Eventos")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AsignadoA");

                    b.Navigation("Empleado");

                    b.Navigation("Estacion");

                    b.Navigation("ReportadoPor");

                    b.Navigation("ResueltoPor");

                    b.Navigation("Turno");

                    b.Navigation("TurnoAsignacion");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.Usuario", b =>
                {
                    b.HasOne("SistemaPeaje.Core.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaPeaje.Core.Entities.Estacion", "Estacion")
                        .WithMany()
                        .HasForeignKey("EstacionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Empleado");

                    b.Navigation("Estacion");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.Carril", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.Cliente", b =>
                {
                    b.Navigation("TarjetasRFID");

                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.Empleado", b =>
                {
                    b.Navigation("Transacciones");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.Estacion", b =>
                {
                    b.Navigation("Carriles");

                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.Liquidacion", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Discrepancias");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.PlcConfiguracion", b =>
                {
                    b.Navigation("CoilsConfiguracion");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.TipoCliente", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.TipoPago", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.TipoVehiculo", b =>
                {
                    b.Navigation("Tarifas");

                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.Turno", b =>
                {
                    b.Navigation("Eventos");

                    b.Navigation("RegistrosTiempo");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.TurnoAsignacion", b =>
                {
                    b.Navigation("Eventos");

                    b.Navigation("RegistrosTiempo");

                    b.Navigation("TurnoEjecutado");
                });

            modelBuilder.Entity("SistemaPeaje.Core.Entities.TurnoTemplate", b =>
                {
                    b.Navigation("TurnoAsignaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
